
spring.application.name=mcp-clientt
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.sse.connections.server1.url=http://localhost:8877
spring.ai.mcp.client.sse.connections.server1.sse-endpoint=/sse
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

server.port=8080

